doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    logging: true
    profiling_collect_backtrace: '%kernel.debug%'
    types:
      product_id: App\Shop\Product\Infrastructure\Persistence\Doctrine\ProductIdType
      promotion_id: App\Shop\Promotion\Infrastructure\Persistence\Doctrine\PromotionIdType

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '15'
  orm:
    auto_generate_proxy_classes: true
    enable_lazy_ghost_objects: true
    report_fields_where_declared: true
    validate_xml_mapping: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    controller_resolver:
      auto_mapping: false
    mappings:
      App\Shop\Product:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Shop/Product/Infrastructure/Persistence/Doctrine'
        prefix: 'App\Shop\Product\Domain'
        alias: App\Shop\Product
      App\Shop\Promotion:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Shop/Promotion/Infrastructure/Persistence/Doctrine'
        prefix: 'App\Shop\Promotion\Domain'
        alias: App\Shop\Promotion
when@test:
  doctrine:
    dbal:
      logging: true
      # "TEST_TOKEN" is typically set by ParaTest
      dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
