name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend-ci:
    name: Build Backend
    runs-on: ubuntu-latest

    env:
      PHP_IMAGE: fredpalas/docker-php-fpm:php-8.2

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

  test-phpunit:
    name: PHPUnit Tests
    runs-on: ubuntu-latest
    needs: build-backend-ci

    env:
      PHP_IMAGE: fredpalas/docker-php-fpm:php-8.2
      COMPOSER_CACHE_DIR: .composer/cache
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mydb_test

    services:
      mysql:
        image: mysql:8.0.29
        options: >-
          --default-authentication-plugin=mysql_native_password
        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: mydb_test
        ports:
          - 3306:3306
        volumes:
          - ./mysql-data:/var/lib/mysql

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run PHPUnit
        run: |
          php -dxdebug.mode=coverage bin/phpunit \
            --log-junit phpunit-report.xml \
            --coverage-cobertura phpunit-coverage.xml \
            --coverage-text \
            --colors=never

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: PHPUnit Reports
          path: |
            phpunit-report.xml
            phpunit-coverage.xml
